Repository G1int/Glint_BE, pull requests merged in 2024-07, with the labels that each got.

#60 [feat]-#40-회원 프로필 구현
  glint/.gitignore
  glint/src/main/java/com/swyp/glint/GlintApplication.java
  glint/src/main/java/com/swyp/glint/keyword/api/DrinkingController.java
  glint/src/main/java/com/swyp/glint/keyword/api/LocationController.java
  glint/src/main/java/com/swyp/glint/keyword/api/ReligionController.java
  glint/src/main/java/com/swyp/glint/keyword/api/SmokingController.java
  glint/src/main/java/com/swyp/glint/keyword/api/UniversityController.java
  glint/src/main/java/com/swyp/glint/keyword/api/WorkController.java
  glint/src/main/java/com/swyp/glint/keyword/application/DrinkingService.java
  glint/src/main/java/com/swyp/glint/keyword/application/LocationService.java
  glint/src/main/java/com/swyp/glint/keyword/application/ReligionService.java
  glint/src/main/java/com/swyp/glint/keyword/application/SmokingService.java
  glint/src/main/java/com/swyp/glint/keyword/application/UniversityService.java
  glint/src/main/java/com/swyp/glint/keyword/application/WorkService.java
  glint/src/main/java/com/swyp/glint/keyword/domain/Drinking.java
  glint/src/main/java/com/swyp/glint/keyword/domain/Location.java
  glint/src/main/java/com/swyp/glint/keyword/domain/Religion.java
  glint/src/main/java/com/swyp/glint/keyword/domain/Smoking.java
  glint/src/main/java/com/swyp/glint/keyword/domain/University.java
  glint/src/main/java/com/swyp/glint/keyword/domain/UniversityCategory.java
  glint/src/main/java/com/swyp/glint/keyword/domain/Work.java
  glint/src/main/java/com/swyp/glint/keyword/domain/WorkCategory.java
  glint/src/main/java/com/swyp/glint/keyword/repository/DrinkingRepository.java
  glint/src/main/java/com/swyp/glint/keyword/repository/LocationRepository.java
  glint/src/main/java/com/swyp/glint/keyword/repository/ReligionRepository.java
  glint/src/main/java/com/swyp/glint/keyword/repository/SmokingRepository.java
  glint/src/main/java/com/swyp/glint/keyword/repository/UniversityCategoryRepository.java
  glint/src/main/java/com/swyp/glint/keyword/repository/UniversityRepository.java
  glint/src/main/java/com/swyp/glint/keyword/repository/WorkCategoryRepository.java
  glint/src/main/java/com/swyp/glint/keyword/repository/WorkRepository.java
  glint/src/main/java/com/swyp/glint/user/api/UserController.java
  glint/src/main/java/com/swyp/glint/user/api/UserDetailController.java
  glint/src/main/java/com/swyp/glint/user/api/UserProfileController.java
  glint/src/main/java/com/swyp/glint/user/application/UserProfileService.java
  glint/src/main/java/com/swyp/glint/user/application/dto/UserDetailRequest.java
  glint/src/main/java/com/swyp/glint/user/application/dto/UserProfileRequest.java
  glint/src/main/java/com/swyp/glint/user/application/dto/UserProfileResponse.java
  glint/src/main/java/com/swyp/glint/user/domain/InformationKeyword.java
  glint/src/main/java/com/swyp/glint/user/domain/User.java
  glint/src/main/java/com/swyp/glint/user/domain/UserDetail.java
  glint/src/main/java/com/swyp/glint/user/domain/UserProfile.java
  glint/src/main/java/com/swyp/glint/user/repository/UserDetailRepository.java
  glint/src/main/java/com/swyp/glint/user/repository/UserProfileRepository.java
  glint/src/main/java/com/swyp/glint/user/repository/UserRepository.java
  glint/src/test/java/com/swyp/glint/user/api/UserProfileControllerTest.java
  glint/src/test/java/com/swyp/glint/user/application/UserProfileServiceTest.java
Labels: Feat

#115 [Feat] #112 회원 프로필 user id로 조회 기능 추가
  glint/src/main/java/com/swyp/glint/user/api/UserDetailController.java
  glint/src/main/java/com/swyp/glint/user/api/UserProfileController.java
Labels: Feat

#139 feat - University와 UniversityCategory의 매핑방식 변경 및 비지니스 로직 수정
  glint/src/main/java/com/swyp/glint/keyword/api/UniversityController.java
  glint/src/main/java/com/swyp/glint/keyword/application/UniversityMappingService.java
  glint/src/main/java/com/swyp/glint/keyword/application/UniversityService.java
  glint/src/main/java/com/swyp/glint/keyword/application/dto/UniversityListResponse.java
  glint/src/main/java/com/swyp/glint/keyword/domain/University.java
  glint/src/main/java/com/swyp/glint/keyword/domain/UniversityCategory.java
  glint/src/main/java/com/swyp/glint/keyword/repository/DrinkingRepository.java
  glint/src/main/java/com/swyp/glint/keyword/repository/LocationRepository.java
  glint/src/main/java/com/swyp/glint/keyword/repository/ReligionRepository.java
  glint/src/main/java/com/swyp/glint/keyword/repository/SmokingRepository.java
  glint/src/main/java/com/swyp/glint/keyword/repository/UniversityCategoryRepository.java
  glint/src/main/java/com/swyp/glint/user/api/UserProfileController.java
  glint/src/main/java/com/swyp/glint/user/application/UserProfileService.java
  glint/src/main/java/com/swyp/glint/user/application/dto/UniversityResponse.java
  glint/src/main/java/com/swyp/glint/user/application/dto/UserProfileWithDetailResponse.java
  glint/src/main/java/com/swyp/glint/user/repository/impl/UserProfileRepositoryImpl.java
  glint/src/main/java/com/swyp/glint/user/repository/impl/UserRepositoryImpl.java
Labels: Feat

#153 [feat] Work와 WorkCategory 매핑방식 수정, Location 수정, 병합 충돌 수정
  glint/src/main/java/com/swyp/glint/keyword/api/LocationController.java
  glint/src/main/java/com/swyp/glint/keyword/api/WorkController.java
  glint/src/main/java/com/swyp/glint/keyword/application/LocationService.java
  glint/src/main/java/com/swyp/glint/keyword/application/UniversityService.java
  glint/src/main/java/com/swyp/glint/keyword/application/WorkCategoryService.java
  glint/src/main/java/com/swyp/glint/keyword/application/WorkMappingService.java
  glint/src/main/java/com/swyp/glint/keyword/application/WorkService.java
  glint/src/main/java/com/swyp/glint/keyword/application/dto/LocationListResponse.java
  glint/src/main/java/com/swyp/glint/keyword/application/dto/WorkCategoryListResponse.java
  glint/src/main/java/com/swyp/glint/keyword/application/dto/WorkListResponse.java
  glint/src/main/java/com/swyp/glint/keyword/domain/Work.java
  glint/src/main/java/com/swyp/glint/keyword/domain/WorkCategory.java
  glint/src/main/java/com/swyp/glint/keyword/repository/LocationRepository.java
  glint/src/main/java/com/swyp/glint/keyword/repository/WorkCategoryRepository.java
  glint/src/main/java/com/swyp/glint/user/api/UserDetailController.java
  glint/src/main/java/com/swyp/glint/user/api/UserProfileController.java
  glint/src/main/java/com/swyp/glint/user/application/UserProfileService.java
  glint/src/main/java/com/swyp/glint/user/application/UserService.java
  glint/src/main/java/com/swyp/glint/user/application/dto/LocationResponse.java
  glint/src/main/java/com/swyp/glint/user/application/dto/UserInfoResponse.java
  glint/src/main/java/com/swyp/glint/user/application/dto/UserLoginResponse.java
  glint/src/main/java/com/swyp/glint/user/application/dto/UserProfileWithDetailResponse.java
  glint/src/main/java/com/swyp/glint/user/repository/impl/UserProfileRepositoryImpl.java
  glint/src/main/java/com/swyp/glint/user/repository/impl/UserRepositoryImpl.java
Labels: Feat, bug, fix

#154 fix: 로그인시 회원가입, 기존회원 로그인 여부 추가
  glint/src/main/java/com/swyp/glint/user/application/UserDetailService.java
  glint/src/main/java/com/swyp/glint/user/application/UserService.java
  glint/src/main/java/com/swyp/glint/user/application/dto/UserLoginResponse.java
  glint/src/main/java/com/swyp/glint/user/domain/UserDetail.java
Labels: fix

#155 [fix] 로그인시 회원가입, 기존회원 로그인 여부 추가 Develop -> Release Merge
  glint/src/main/java/com/swyp/glint/user/application/UserDetailService.java
  glint/src/main/java/com/swyp/glint/user/application/UserService.java
  glint/src/main/java/com/swyp/glint/user/application/dto/UserLoginResponse.java
  glint/src/main/java/com/swyp/glint/user/domain/UserDetail.java
Labels: fix

#159 Feat #158 미팅방 수정
  glint/src/main/java/com/swyp/glint/auth/application/social/KakaoOauth.java
  glint/src/main/java/com/swyp/glint/common/exception/ErrorCode.java
  glint/src/main/java/com/swyp/glint/meeting/api/MeetingController.java
  glint/src/main/java/com/swyp/glint/meeting/application/MeetingFacade.java
  glint/src/main/java/com/swyp/glint/meeting/application/MeetingService.java
  glint/src/main/java/com/swyp/glint/meeting/domain/Meeting.java
  glint/src/main/java/com/swyp/glint/meeting/exception/AlreadyJoinMeetingException.java
  glint/src/main/java/com/swyp/glint/user/application/UserProfileService.java
Labels: Feat

#164 fix: 미팅방 검색 location 추가
  glint/src/main/java/com/swyp/glint/meeting/application/MeetingFacade.java
  glint/src/main/java/com/swyp/glint/meeting/domain/Meeting.java
  glint/src/main/java/com/swyp/glint/meeting/repository/impl/MeetingRepositoryImpl.java
Labels: fix

#167 fix: 미팅 검색 지역 필터 추가
  glint/src/main/java/com/swyp/glint/meeting/application/dto/MeetingSearchCondition.java
  glint/src/main/java/com/swyp/glint/meeting/repository/impl/MeetingRepositoryImpl.java
Labels: fix

#168 Develop -> Release Merge #166 미팅 검색 지역필터 추가
  glint/src/main/java/com/swyp/glint/meeting/application/dto/MeetingSearchCondition.java
  glint/src/main/java/com/swyp/glint/meeting/repository/impl/MeetingRepositoryImpl.java
  glint/src/main/resources/application.yaml
Labels: fix

#171 Develop -> Release Merge #169 미팅 참가신청 중복 불가
  glint/src/main/java/com/swyp/glint/meeting/application/MeetingFacade.java
  glint/src/main/java/com/swyp/glint/meeting/repository/JoinMeetingRepository.java
Labels: fix
